### ISSUE TITLE
ModuleNotFoundError: No module named 'sortedcontainers'

### ISSUE THREAD

**Issue by fmors** [dsoftwareinc/fakeredis-py#24] opened 2022-05-25 14:26 UTC
**Describe the bug**
Using fakeredis 1.7.6 on unit tests automated by tox gives a `ModuleNotFoundError: No module named 'sortedcontainers'`. This error does not happen on 1.7.5. Maybe `sortedcontainers` should be added as a dependency?

**To Reproduce**
1. Create a unit test that uses fakeredis 1.7.6
2. Run unit test on a clean virtualenv created by tox
3. See error

**Expected behavior**
`sortedcontainers` should be installed together with `fakeredis` as a dependency

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - python 3.8.10

**Additional context**
N/A

**Comment by Jamie-** [comment] 2022-05-25 14:29
Seems to be a dupe of https://github.com/dsoftwareinc/fakeredis-py/issues/23

**Comment by fmors** [comment] 2022-05-25 14:34
Yes @Jamie- , it is a duplicate. While I was creating this bug report, the #23 was logged :)

**Closed** 2022-05-25 14:36 UTC
Labels: bug
